# Generated by Django 4.0.4 on 2022-06-01 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='GoogleAnalyticsApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='UID')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('view_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Counter Number')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Google Analytics АПИ',
                'verbose_name_plural': 'Google Analytics АПИ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OzonApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='UID')),
                ('apikey', models.CharField(blank=True, max_length=100, null=True, verbose_name='API Key')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Ozon API',
                'verbose_name_plural': 'Ozon API',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='UID')),
                ('amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сумма')),
                ('count', models.CharField(blank=True, max_length=100, null=True, verbose_name='Количество')),
                ('date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата')),
                ('marketplace', models.CharField(blank=True, max_length=100, null=True, verbose_name='Маркетплейс')),
                ('product', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип продукта')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WildberriesApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='UID')),
                ('apikey', models.CharField(blank=True, max_length=100, null=True, verbose_name='API Key')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Wildberries API',
                'verbose_name_plural': 'Wildberries API',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='YandexDirectApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='UID')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('apikey', models.CharField(blank=True, max_length=100, null=True, verbose_name='API Key')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Яндекс Директ АПИ',
                'verbose_name_plural': 'Яндекс Директ АПИ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='YandexMetrikaApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='UID')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('counter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Counter Number')),
                ('apikey', models.CharField(blank=True, max_length=100, null=True, verbose_name='API Key')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Яндекс Метрика АПИ',
                'verbose_name_plural': 'Яндекс Метрика АПИ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Текст статьи')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='algoritm.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Наши услуги',
                'verbose_name_plural': 'Наши услуги',
                'ordering': ['pk'],
            },
        ),
    ]
